### ISSUE TITLE
About use ZYYT with Carthage 

### ISSUE THREAD

**Issue by liuzhiyi1992** [Dershowitz011/ZYYT#1]
yeah,  xcode 7.3 updated version.

1.deploy ZYTT.framework in [project -> target -> Embedded Binaries
2.import ZYTT
3.create ZYThumbnailTableViewController object
4.but can not access the property about it

**Comment by Dershowitz011** [comment]
Give me 15 mins to figure out @liuzhiyi1992 . Don't disappear lol. :laughing:

**Comment by liuzhiyi1992** [comment]
hah，this is my first time to touch Carthage

**Comment by Dershowitz011** [comment]
Fixed. Update it using `Carthage update ZYYT` and let me know if any problem still persists. :) @liuzhiyi1992 and add it in linked frameworks and not in embedded binaries.

**Comment by liuzhiyi1992** [comment]
what about difference between in linked frameworks or embedded binaries

**Comment by Dershowitz011** [comment]
Many experts suggest for iOS to add frameworks in linked frameworks section. I really don't know how they differ as both do the job but anyhow. it's working?

**Comment by liuzhiyi1992** [comment]
before:  
![](https://raw.githubusercontent.com/liuzhiyi1992/MyStore/master/ZYThumbnailTableView/tmp.png)  

after:  
![](https://raw.githubusercontent.com/liuzhiyi1992/MyStore/master/ZYThumbnailTableView/tmp2.png)  

but the Blocks:  
![](https://raw.githubusercontent.com/liuzhiyi1992/MyStore/master/ZYThumbnailTableView/issues3.png)

**Comment by Dershowitz011** [comment]
Problem only with blocks right? @liuzhiyi1992

**Comment by liuzhiyi1992** [comment]
yeah

**Comment by Dershowitz011** [comment]
Fixed. Try now @liuzhiyi1992 ? Update and try.

**Comment by liuzhiyi1992** [comment]
Fixed, and what did you do for it

**Comment by Dershowitz011** [comment]
Had to make the type aliases public in order for it to be used in another class. You don't need to change anything. All problems fixed? Works like a charm?

**Comment by liuzhiyi1992** [comment]
Wait a moment

**Comment by Dershowitz011** [comment]
Heading out for a while. Please please change whatever u need to in the classes. I'll come back and merge and thanks a lot for letting me make your code a library. See you soon.

**Comment by liuzhiyi1992** [comment]
while run the project:
![](https://raw.githubusercontent.com/liuzhiyi1992/MyStore/master/ZYThumbnailTableView/issues4.png)

I can not think what is the reason.

**Comment by liuzhiyi1992** [comment]
maybe, you should go to rest. see you tomorrow

**Comment by Dershowitz011** [comment]
Hey @liuzhiyi1992 . Add it to embedded libraries and frameworks then. It should work. This is one error i don't know why it'll come but when u add the framework in embedded libraries and framework it will be resolved.

**Comment by liuzhiyi1992** [comment]
work! I'm very glad to chat with you

**Comment by Dershowitz011** [comment]
Likewise @liuzhiyi1992 . Whenever you update anything in your repo, update it in this repo too and I'll merge the request. okay? Closing this issue now. Thanks.
